### ISSUE TITLE
egs_brachy fails to compile at configure and cannot make

### ISSUE THREAD

**Issue by Mighty-Raindeer** [clrp-code/egs_brachy#25]
egs_brachy output failed in initial compiling on configure, along with mird. When attempting to make specifically on egs_brachy, i encounter the attached error.

[egs_brachy make error.txt](https://github.com/clrp-code/egs_brachy/files/8044325/egs_brachy.make.error.txt)

**Comment by MartinMartinov** [comment]
Interesting, another c++11 error, though this one doesn't have as smooth a solution.  Would you mind adding the following:

```-std=c++11```

to the end of line 62 to the Makefile in your egs_brachy directory.  The whole line will probably look something like this:

```INCL = -g -Wall -Wno-sign-compare $(TURN_OFF_MACOS_WARNINGS) -I. -I.$(DSEP)gzstream -I$(HEN_HOUSE)lib$(DSEP)$(my_machine) -I$(abs_egspp) -I$(abs_egspp)$(DSEP)geometry -I$(egs_interface) -I$(HEN_HOUSE)iaea_phsp -I.$(DSEP)zlib -std=c++11```

and then see if a recompiling works.

**Comment by Mighty-Raindeer** [comment]
This fixed the initial compiling failure for egs_brachy. egs_mird still fails to compile. 

egs_brachy make outputs a different error now (missing file/directory) 

I will paste both errors here. I can make the egs_mird a separate issue thread if you'd prefer.
[egs_mird make error.txt](https://github.com/clrp-code/egs_brachy/files/8050013/egs_mird.make.error.txt)
[egs_brachy make error.txt](https://github.com/clrp-code/egs_brachy/files/8050014/egs_brachy.make.error.txt)

**Comment by MartinMartinov** [comment]
No, it's fine, problem solving here for both works.

For the egs_brachy error, can you check to make sure your EGS_HOME and HEN_HOUSE variables in your bashrc file have a ```/``` character at the end.  I think the issue is one might be missing at the end of your EGS_HOME definition.

As for egs_mird, this will require two changes.  The first, egs_mird.cpp in HEN_HOUSE/user_code/egs_mird.cpp requires a change: the line ```#include <sstream>``` must be added amongst the include lines at the top.  I've also pushed the change the EGSnrc_CLRP if you wanted to pull it the change yourself.  The second issue is that egs_mird's makefile depends on the egs++ compiler options, so you'll need to run ```configure``` again and reinstall your HEN_HOUSE and EGS_HOME areas.  As you are installing, after selecting your c++ compiler, you'll get asked for any additional flags.  You'll want to select optimization flags then enter ```-std=c++11``` before continuing.  Demonstrated below:

```
Using the following compiler/linker switches for creating/linking against
dynamic shared objects (DSO, also known as shared library or DLL), where
$(abs_dso) or $(ABS_DSO) below will be replaced with the absolute path to the
EGSnrc DSO directory at compile/link time:

1) Optimization options:                          -O2 -mtune=native
2) Generation of position independent code:       -fPIC
3) Preprocessor defines:
4) Flag for creating shared libraries:            -shared
5) Output/dlopen library:                         -o $@ -ldl
6) DSO path encoded in the executable:            -L$(abs_dso) -Wl,-rpath,$(abs_dso)
7) Linking against library some_lib:              -lsome_lib
8) Fortran libraries needed by C++ linker:        -lgfortran -lquadmath

Input option to change, or enter to proceed:      1
Input Optimization options:                       -std=c++11

**Comment by Mighty-Raindeer** [comment]
Thanks Martin,

You are right about adding / to the EGS_HOMe and HEN_HOUSE variables, and that fixed that issue. 

I then recloned EGSnrc_with_egs_brachy and using the optimization flag you mentioned, mird compiled successfully. BUT, now the egs_brachy folder in HEN_HOUSE/user_codes is empty after the clone.

**Comment by MartinMartinov** [comment]
Did you use the command with recurse submodules enabled? (ie, ```git clone --recurse-submodules https://github.com/clrp-code/EGSnrc_CLRP.git```)  I know it has been finicky in the past, so it wouldn't surprise me if it still didn't work.  Another option is to manually clone egs_brachy somewhere else like your home area (ie, ```git clone https://github.com/clrp-code/egs_brachy.git```) and then copy the directory that contains egs_brachy.cpp (a little confusing since there is a nested egs_brachy directory) to your egs_home area and just compile from there.

**Comment by Mighty-Raindeer** [comment]
Success! Everything has compiled. Thank you for the help

**Comment by MartinMartinov** [comment]
Awesome!  Glad to hear it :)
