### ISSUE TITLE
Difference in scoring in egs_brachy

### ISSUE THREAD

**Issue by subha18** [clrp-code/egs_brachy#26]
I want to score Dmm and Dwm for a prostate permanent implant. The geometry mainly consists of a egsphant file generated using ctcreate from DICOM images of a prostate implant. It has body tissues (supplied in ramp file) as media and 57 number of 125I sources are embedded in it. I tried to run the simulation and score Dmm and Dwm using  tracklength estimator. The run finished with no errors. However, Got score for Dmm but zero values for Dwm in all the voxels. I have noticed that if the material (water in this case) is not a part of the geometry, the scoring is not done. 

As per my understanding, for scoring Dwm the radiation transport is being carried out in CT anatomy but dose to water is scored. I believe my scores using tracklenth estimator should not be limited to the media present in the geometry since the muen/rho data supplied should be able to take care of this. **Else how to estimate different scoring options as suggested by TG186.** 

I scored using energy deposition estimator as well. There i believe dose is deposited in actual voxel media we have no option of scoring Dwm. I got identical Dmm and Dwm values. **### Please help me to understand the difference of these two estimators which have same units i.e Gy/history.**

**Comment by rfmthoms** [comment]
To score Dwm, a "muen for medium" block needs to be used in the scoring block.  Please take a look at the technical reference manual (https://clrp-code.github.io/egs_brachy/) "scoring options", in particular:
'muen for medium': (Optional) one or more input blocks which specify the muen dataset to be used for a given transport medium. (Can be used instead of or in conjunction with muen for media) This allows you to, for example, transport particles in tissue but score in water with notation Dw,m according to the conventions of TG-186.
See example there.

**Comment by subha18** [comment]
Yes, I got the results.
Thank You
