### ISSUE TITLE
egs_brachy_technical_manual.pdf missing

### ISSUE THREAD

**Issue by dworogers** [clrp-code/egs_brachy#57]
Clicking on the link for [egs_brachy_technical_manual.pdf](https://github.com/clrp-code/egs_brachy/blob/main/docs/pdf/egs_brachy_technical_manual.pdf) uploads a 2.7 kB blank file.

**Comment by mchamberland** [comment]
@dworogers Right, I noticed this when I updated the documentation last time. I could not figure out how to fix it and I felt it was not worth my time to investigate further since the documentation is available both locally (i.e., in the source code repository) and online, with much better formatting than the PDF. 

I should remove the link to the PDF and the blank PDF.

**Comment by dworogers** [comment]
Agreed Marc. Just removing is better since I couldn't figure out if it was my mistake somehow.
