### ISSUE TITLE
egs_brachy allows seeds to overlap

### ISSUE THREAD

**Issue by rfmthoms** [clrp-code/egs_brachy#8]
egs_brachy running in "normal" mode will run with seeds that overlap - shouldn't happen in this run mode because is unphysical.  Add check in geometry initialization (perhaps during region discovery) for source geometries that overlap?  Throw warning? Or stop?

**Comment by randlet** [comment]
Hi Rowan,

Off the top of my head I think::

* during region discovery will not work in all cases, since the region discovery is only done if using the AutoEnvelope geometry
* could also be done during volume correction, but I think this has the same problem that volume correction is not always done

I think two approaches that would work in general would be to either:

a) do an analytical calculation to determine whether the boundary shapes of any seeds overlap each other.  This would require writing routines to check intersections of cylinders, spheres and boxes.  I suspect that is possible but difficult!

b) do a separate MC simulation that is very similar to the volume corrections: generate points in each sources bounding shape and check if the point lands in a source other than the one currently being checked.

Method b) is likely easiest and probably still pretty fast.  It could also be opt-in (opt-out?) so that in cases where you know sources don't overlap you could skip the check.

**Comment by rfmthoms** [comment]
Hi Randy,
Great thoughts and ideas, as always!  :)
Agreed that option (b) is best, and it's a good idea to make it opt-in/out in case the user either knows sources don't overlap and doesn't want to spend time on it.
This came up in simulating clinical patient data - post implant CTs have artifacts and so source positions+orientations are not accurately known.
Thanks!

**Comment by randlet** [comment]
Initial version of this functionality committed in d3f72fd1d2

**Comment by randlet** [comment]
Deleted previous comment/commits. After more thought/experimentation it turned out to be a much harder problem than I originally thought.

**Comment by randlet** [comment]
Take 2 implemented in 62daf2bc71a0
